# Основная конфигурация для проекта детекции штрих-кодов

# Общие настройки
project_name: "barcode-detection"
seed: 42
device: "auto"  # auto, cpu, cuda

# Директории
data_dir: "data"
output_dir: "outputs"
logs_dir: "logs"
plots_dir: "plots"

# Конфигурация данных
data:
  data_dir: ${data_dir}
  train_path: "train"
  val_path: "val"
  test_path: "test"
  image_size: 640
  image_extensions: [".jpg", ".jpeg", ".png"]
  annotation_format: "json"  # json или yolo
  
  # Аугментации
  augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.2
    rotation: 15
    brightness: 0.2
    contrast: 0.2

# Конфигурация модели
model:
  name: "yolov8n.pt"  # yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  num_classes: 5  # qr, datamatrix, pdf417, ean13, other
  pretrained: true

# Конфигурация обучения
training:
  epochs: 50
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.0005
  num_workers: 4
  pin_memory: true
  mixed_precision: true
  
  # Early stopping
  early_stopping: true
  patience: 10
  
  # Checkpoint
  save_top_k: 3
  monitor: "val_loss"
  mode: "min"
  save_last: true

# Конфигурация инференса
inference:
  model_path: "${output_dir}/best.pt"
  confidence_threshold: 0.5
  iou_threshold: 0.45
  max_detections: 100
  input_size: 640
  device: ${device}

# MLflow конфигурация
mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "barcode_detection"
  autolog: true
  log_models: true

# Логирование
logging:
  level: "INFO"
  log_file: null
  log_dir: ${logs_dir}

# Классы штрих-кодов
classes:
  names: ["qr", "datamatrix", "pdf417", "ean13", "other"]
  colors: 
    - [255, 0, 0]    # красный для QR
    - [0, 255, 0]    # зеленый для DataMatrix
    - [0, 0, 255]    # синий для PDF417
    - [255, 255, 0]  # желтый для EAN13
    - [255, 0, 255]  # пурпурный для other
